name: Build - Test - Push

on:
  push:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUILD_FOLDER: ./build/packer

jobs:
  # https://www.codewrecks.com/post/github/choose-environment-from-branch/
  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
  branch:
    name: Get branch name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: branch-check
        run: |
          echo "Is on Github Actions ${GITHUB_ACTIONS}"
          if [[ "true" == "${GITHUB_ACTIONS}" ]]; then
            echo "GITHUB_ACTIONS is TRUE"
          else
            echo "GITHUB_ACTIONS is FALSE"
          fi
          
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
             echo "env_name=sandbox" >> $GITHUB_OUTPUT
          fi
    outputs:
      env_name: ${{ steps.branch-check.outputs.env_name }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Download Dependencies
        run: |
          make dependencies

      - name: Unpack OpenApi
        run: |
          make unpack

      - name: Build for Production
        run: |
          make build          

      - name: Upload Github OpenApi client.sh
        uses: actions/upload-artifact@v3
        with:
          name: github-openapi-client
          path: pkg/adaptors/github/openapi/client.sh

      - name: Upload Dist file
        uses: actions/upload-artifact@v3
        with:
          name: build-file
          path: build/semver

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download Github OpenApi client.sh
        uses: actions/download-artifact@v3
        with:
          name: github-openapi-client
          path: pkg/adaptors/github/openapi

      - name: Download Dist file
        uses: actions/download-artifact@v3
        with:
          name: build-file
          path: build

      - name: Run Unit Tests
        run: |
          chmod u+x build/*
          chmod u+x pkg/adaptors/github/openapi/*
          make unit-tests

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
    permissions: write-all    
    env:
      GITHUB_PAT_OWNER: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT_CONTRIBUTOR: ${{ secrets.GH_PAT_BOT_CONTRIBUTOR }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download Github OpenApi client.sh
        uses: actions/download-artifact@v3
        with:
          name: github-openapi-client
          path: pkg/adaptors/github/openapi

      - name: Download Dist file
        uses: actions/download-artifact@v3
        with:
          name: build-file
          path: build

      - name: Setup E2E Test environment
        run: |
          project_root=$(pwd)
          git clone https://oauth2:${GITHUB_PAT_OWNER}@github.com/BeanGithubSandboxUpstream/semver-bash.git test/sandbox/github/upstream
          git clone https://oauth2:${GITHUB_PAT_CONTRIBUTOR}@github.com/PeterBeanBotContributor/semver-bash.git test/sandbox/github/contributor
                    
          cd "${project_root}"/test/sandbox/github/upstream
          git config user.email "upstream.bot@peterbean.net"
          git config user.name "Upstream Bot"
          
          cd "${project_root}"/test/sandbox/github/contributor
          git config user.email "contributor.bot@peterbean.net"
          git config user.name "Contributor Bot"
        
      - name: Run E2E Tests
        run: |
          sudo apt install ncat -y
          chmod u+x build/*
          chmod u+x pkg/adaptors/github/openapi/*
          make e2e-tests